### ISSUE TITLE
Can you add a LICENSE?

### ISSUE THREAD

**Issue by bighuang624** [JustClear/blurify#8]
Hi! 

I'm a college student and now in charge of the development of a competition project. I prefer your work, but I wonder if I can use it in my project because it could turn into a business project. 

Can you add a LICENSE to let me know whether you allow people like me to use blurify.js in such projects?

Thanks a lot!

**Comment by JustClear** [comment]
Of course you can, any problems in use can be sent back to here to give me feedback.
